name: mysql_with_dartfrog
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dart_frog: ^1.0.1
  mysql_client: ^0.0.27
  cloudinary: ^1.2.0
  tuple: ^2.0.1
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.12.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
